name: Update Assets
on: 
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  generate:
    name: Update Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run updater
        run: |
          pip install requests
          python update.py
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Assets ${AssetsVersion}"
      - name: Push changes
        continue-on-error: false
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}